	alter TABLE  FILES ADD CREATED_SID   VARCHAR(37) NOT NULL;
	alter TABLE  FILES ADD CREATED_BY    VARCHAR(37) NOT NULL;
	alter TABLE  FILES ADD CREATED_ON    TIMESTAMP NOT NULL;
	alter TABLE  FILES ADD UPDATED_SID   VARCHAR(37);
	alter TABLE  FILES ADD UPDATED_BY    VARCHAR(37);
	alter TABLE  FILES ADD UPDATED_ON    TIMESTAMP;